//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MineMovie_Nhom7_CNPM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DANH_GIA
    {
        public int ID_DG { get; set; }
        public string BINH_LUAN { get; set; }
        public Nullable<int> SO_SAO { get; set; }
        public Nullable<System.DateTime> NGAY_DG { get; set; }
        public Nullable<int> ID_ND { get; set; }
        public Nullable<int> ID_PHIM { get; set; }
    
        public virtual CHI_TIET_PHIM CHI_TIET_PHIM { get; set; }
        public virtual NGUOI_DUNG NGUOI_DUNG { get; set; }
    }
}
