//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MineMovie_Nhom7_CNPM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DS_YEU_THICH
    {
        public int ID_DS { get; set; }
        public Nullable<System.DateTime> NGAY_THEM { get; set; }
        public Nullable<int> SO_LUONG { get; set; }
    }
}
