//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MineMovie_Nhom7_CNPM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KH_PHIM_DSYT
    {
        public int ID_PHIM { get; set; }
        public int ID_DS { get; set; }
        public Nullable<System.DateTime> NGAY_THEM { get; set; }
    
        public virtual CHI_TIET_PHIM CHI_TIET_PHIM { get; set; }
        public virtual DS_YEU_THICH DS_YEU_THICH { get; set; }
    }
}
