//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MineMovie_Nhom7_CNPM.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class MINEMOVIEEntities : DbContext
    {
        public MINEMOVIEEntities()
            : base("name=MINEMOVIEEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CHI_TIET_PHIM> CHI_TIET_PHIM { get; set; }
        public virtual DbSet<DANH_GIA> DANH_GIA { get; set; }
        public virtual DbSet<DS_YEU_THICH> DS_YEU_THICH { get; set; }
        public virtual DbSet<KH_PHIM_DSYT> KH_PHIM_DSYT { get; set; }
        public virtual DbSet<KH_PHIM_RAP> KH_PHIM_RAP { get; set; }
        public virtual DbSet<NGUOI_DUNG> NGUOI_DUNG { get; set; }
        public virtual DbSet<PHIM> PHIMs { get; set; }
        public virtual DbSet<RAP_PHIM> RAP_PHIM { get; set; }
        public virtual DbSet<THE_LOAI> THE_LOAI { get; set; }
    
        public virtual int procDangKiNguoiDung(string tentk, string gmail, string mk, string ava)
        {
            var tentkParameter = tentk != null ?
                new ObjectParameter("tentk", tentk) :
                new ObjectParameter("tentk", typeof(string));
    
            var gmailParameter = gmail != null ?
                new ObjectParameter("gmail", gmail) :
                new ObjectParameter("gmail", typeof(string));
    
            var mkParameter = mk != null ?
                new ObjectParameter("mk", mk) :
                new ObjectParameter("mk", typeof(string));
    
            var avaParameter = ava != null ?
                new ObjectParameter("ava", ava) :
                new ObjectParameter("ava", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("procDangKiNguoiDung", tentkParameter, gmailParameter, mkParameter, avaParameter);
        }
    
        public virtual ObjectResult<string> procDangNhapNguoiDung(string tentk, string mk)
        {
            var tentkParameter = tentk != null ?
                new ObjectParameter("tentk", tentk) :
                new ObjectParameter("tentk", typeof(string));
    
            var mkParameter = mk != null ?
                new ObjectParameter("mk", mk) :
                new ObjectParameter("mk", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("procDangNhapNguoiDung", tentkParameter, mkParameter);
        }
    
        public virtual ObjectResult<Nullable<bool>> procKiemTraPhimYeuThich(Nullable<int> idND, Nullable<int> idPhim)
        {
            var idNDParameter = idND.HasValue ?
                new ObjectParameter("idND", idND) :
                new ObjectParameter("idND", typeof(int));
    
            var idPhimParameter = idPhim.HasValue ?
                new ObjectParameter("idPhim", idPhim) :
                new ObjectParameter("idPhim", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<bool>>("procKiemTraPhimYeuThich", idNDParameter, idPhimParameter);
        }
    
        public virtual int procThemPhimYeuThich(Nullable<int> idND, Nullable<int> idPhim)
        {
            var idNDParameter = idND.HasValue ?
                new ObjectParameter("idND", idND) :
                new ObjectParameter("idND", typeof(int));
    
            var idPhimParameter = idPhim.HasValue ?
                new ObjectParameter("idPhim", idPhim) :
                new ObjectParameter("idPhim", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("procThemPhimYeuThich", idNDParameter, idPhimParameter);
        }
    
        public virtual ObjectResult<procThongTinNguoiDung_Result> procThongTinNguoiDung(string tentk)
        {
            var tentkParameter = tentk != null ?
                new ObjectParameter("tentk", tentk) :
                new ObjectParameter("tentk", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<procThongTinNguoiDung_Result>("procThongTinNguoiDung", tentkParameter);
        }
    
        public virtual ObjectResult<procTimKiemPhim_Result> procTimKiemPhim(string tuKhoa)
        {
            var tuKhoaParameter = tuKhoa != null ?
                new ObjectParameter("TuKhoa", tuKhoa) :
                new ObjectParameter("TuKhoa", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<procTimKiemPhim_Result>("procTimKiemPhim", tuKhoaParameter);
        }
    
        public virtual int procXoaPhimYeuThich(Nullable<int> idND, Nullable<int> idPhim)
        {
            var idNDParameter = idND.HasValue ?
                new ObjectParameter("idND", idND) :
                new ObjectParameter("idND", typeof(int));
    
            var idPhimParameter = idPhim.HasValue ?
                new ObjectParameter("idPhim", idPhim) :
                new ObjectParameter("idPhim", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("procXoaPhimYeuThich", idNDParameter, idPhimParameter);
        }
    }
}
