//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MineMovie_Nhom7_CNPM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NGUOI_DUNG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NGUOI_DUNG()
        {
            this.DANH_GIA = new HashSet<DANH_GIA>();
        }
    
        public int ID_ND { get; set; }
        public string TEN_ND { get; set; }
        public string GMAIL { get; set; }
        public string MAT_KHAU { get; set; }
        public string CHUC_VU { get; set; }
        public string ANH_DAI_DIEN { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DANH_GIA> DANH_GIA { get; set; }
    }
}
