//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MineMovie_Nhom7_CNPM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RAP_PHIM
    {
        public int ID_RAP { get; set; }
        public string TEN_RAP { get; set; }
        public string WEBSITE { get; set; }
    }
}
